version: '3.9'

services:
  java_app:
    container_name: java_app
    image: my-albums
    build: .
    ports:
      - "8080:8080"
    links:
      - albums_db
    environment:
      - spring.datasource.url=jdbc:mysql://albums_db:3306/albums_db?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=bd123
    depends_on:
      - albums_db

  albums_db:
    container_name: albums_db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bd123
      - MYSQL_DATABASE=albums_db
    ports:
      - "3307:3306"